/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;
import Vues.frmMenu;
import Entity.Individus;
import Entity.FonctionsMetier;
import Model.ModelIndividu;
import javax.swing.JOptionPane;

/**
 *
 * @author natha
 */
public class frmListeTypeIndividus extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frmListeTypeIndividus
     */
    
    FonctionsMetier fm;
    ModelIndividu mdlIndividu;
 
    public frmListeTypeIndividus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIndividus = new javax.swing.JTable();
        btnInsererIndividu = new javax.swing.JButton();
        btnModifierIndividu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Type d'individus");

        tblIndividus.setBackground(new java.awt.Color(255, 255, 255));
        tblIndividus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Libelle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIndividus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIndividusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIndividus);

        btnInsererIndividu.setBackground(new java.awt.Color(0, 153, 255));
        btnInsererIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnInsererIndividu.setText("Insérer un individu");
        btnInsererIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererIndividuMouseClicked(evt);
            }
        });
        btnInsererIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsererIndividuActionPerformed(evt);
            }
        });

        btnModifierIndividu.setBackground(new java.awt.Color(0, 153, 255));
        btnModifierIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierIndividu.setText("Modifier un individu");
        btnModifierIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierIndividuMouseClicked(evt);
            }
        });
        btnModifierIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierIndividuActionPerformed(evt);
            }
        });

        jLabel2.setText("Libellé :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(btnInsererIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnModifierIndividu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnInsererIndividu)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnModifierIndividu)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsererIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsererIndividuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsererIndividuActionPerformed

    private void btnInsererIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererIndividuMouseClicked
        // TODO add your handling code here:
        
        frmInsererTypesIndividus insererTypeIndividus = new frmInsererTypesIndividus();
        insererTypeIndividus.setVisible(true);
    }//GEN-LAST:event_btnInsererIndividuMouseClicked

    private void btnModifierIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierIndividuMouseClicked
        // TODO add your handling code here:
        
        if(tblIndividus.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"Sélectionner un type d'individu","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            fm.ModifierIndividu(txtLibelle.getText(), Integer.parseInt(tblIndividus.getValueAt(tblIndividus.getSelectedRow(), 0).toString()));
            mdlIndividu = new ModelIndividu();
            mdlIndividu.loadDatas(fm.GetAllIndividus());
            tblIndividus.setModel(mdlIndividu);
        }
        
       
    }//GEN-LAST:event_btnModifierIndividuMouseClicked

    private void btnModifierIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierIndividuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierIndividuActionPerformed

    private void tblIndividusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIndividusMouseClicked
        // TODO add your handling code here:
        
        txtLibelle.setText(tblIndividus.getValueAt(tblIndividus.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tblIndividusMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ConnexionBDD bdd = new ConnexionBDD(); 
        fm = new FonctionsMetier();
        mdlIndividu = new ModelIndividu();
        mdlIndividu.loadDatas(fm.GetAllIndividus());
        tblIndividus.setModel(mdlIndividu);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListeTypeIndividus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsererIndividu;
    private javax.swing.JButton btnModifierIndividu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIndividus;
    private javax.swing.JTextField txtLibelle;
    // End of variables declaration//GEN-END:variables
}
