/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;


/**
 *
 * @author natha
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCompte = new javax.swing.JButton();
        btnTypesIndividus = new javax.swing.JButton();
        btnMedicaments = new javax.swing.JButton();
        btnPrescriptions = new javax.swing.JButton();
        btnMedicamentsNonConseilles = new javax.swing.JButton();
        btnStatistiques = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCompte.setBackground(new java.awt.Color(51, 51, 51));
        btnCompte.setForeground(new java.awt.Color(255, 255, 255));
        btnCompte.setText("Déconnexion");
        btnCompte.setActionCommand("");
        btnCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompteMouseClicked(evt);
            }
        });
        btnCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompteActionPerformed(evt);
            }
        });

        btnTypesIndividus.setBackground(new java.awt.Color(0, 153, 255));
        btnTypesIndividus.setForeground(new java.awt.Color(255, 255, 255));
        btnTypesIndividus.setText("Liste des types d'individus");
        btnTypesIndividus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTypesIndividusMouseClicked(evt);
            }
        });
        btnTypesIndividus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypesIndividusActionPerformed(evt);
            }
        });

        btnMedicaments.setBackground(new java.awt.Color(0, 153, 255));
        btnMedicaments.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicaments.setText("Liste des médicaments");
        btnMedicaments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicamentsMouseClicked(evt);
            }
        });
        btnMedicaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentsActionPerformed(evt);
            }
        });

        btnPrescriptions.setBackground(new java.awt.Color(0, 153, 255));
        btnPrescriptions.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescriptions.setText("Insérer une prescription");
        btnPrescriptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrescriptionsMouseClicked(evt);
            }
        });
        btnPrescriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionsActionPerformed(evt);
            }
        });

        btnMedicamentsNonConseilles.setBackground(new java.awt.Color(0, 153, 255));
        btnMedicamentsNonConseilles.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicamentsNonConseilles.setText("Liste des médicaments non conseillés");
        btnMedicamentsNonConseilles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicamentsNonConseillesMouseClicked(evt);
            }
        });
        btnMedicamentsNonConseilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentsNonConseillesActionPerformed(evt);
            }
        });

        btnStatistiques.setBackground(new java.awt.Color(0, 153, 255));
        btnStatistiques.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistiques.setText("Les statistiques");
        btnStatistiques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatistiquesMouseClicked(evt);
            }
        });
        btnStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistiquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTypesIndividus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrescriptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMedicamentsNonConseilles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMedicaments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStatistiques, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCompte)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCompte)
                .addGap(57, 57, 57)
                .addComponent(btnTypesIndividus)
                .addGap(40, 40, 40)
                .addComponent(btnMedicaments)
                .addGap(38, 38, 38)
                .addComponent(btnPrescriptions)
                .addGap(42, 42, 42)
                .addComponent(btnMedicamentsNonConseilles)
                .addGap(46, 46, 46)
                .addComponent(btnStatistiques)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompteActionPerformed

    private void btnTypesIndividusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypesIndividusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTypesIndividusActionPerformed

    private void btnMedicamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicamentsActionPerformed

    private void btnPrescriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrescriptionsActionPerformed

    private void btnMedicamentsNonConseillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentsNonConseillesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicamentsNonConseillesActionPerformed

    private void btnStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistiquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatistiquesActionPerformed

    private void btnTypesIndividusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTypesIndividusMouseClicked
        // TODO add your handling code here:
        
        frmListeTypeIndividus typeIndividus = new frmListeTypeIndividus();
        typeIndividus.setVisible(true);
    }//GEN-LAST:event_btnTypesIndividusMouseClicked

    private void btnMedicamentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicamentsMouseClicked
        // TODO add your handling code here:
        
        frmMedicamentEtInformation medicamentInfos = new frmMedicamentEtInformation();
        medicamentInfos.setVisible(true);
    }//GEN-LAST:event_btnMedicamentsMouseClicked

    private void btnPrescriptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescriptionsMouseClicked
        // TODO add your handling code here:
        frmPrescription prescription = new frmPrescription();
        prescription.setVisible(true);
    }//GEN-LAST:event_btnPrescriptionsMouseClicked

    private void btnMedicamentsNonConseillesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicamentsNonConseillesMouseClicked
        // TODO add your handling code here:
        
        frmMedicamentNonConseillé medocNonConseille = new frmMedicamentNonConseillé();
        medocNonConseille.setVisible(true);
    }//GEN-LAST:event_btnMedicamentsNonConseillesMouseClicked

    private void btnStatistiquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistiquesMouseClicked
        // TODO add your handling code here:
        frmStats stats = new frmStats();
        stats.setVisible(true);
    }//GEN-LAST:event_btnStatistiquesMouseClicked

    private void btnCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompteMouseClicked
        // TODO add your handling code here:
        
        frmIndentification identification = new frmIndentification();
        identification.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCompteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompte;
    private javax.swing.JButton btnMedicaments;
    private javax.swing.JButton btnMedicamentsNonConseilles;
    private javax.swing.JButton btnPrescriptions;
    private javax.swing.JButton btnStatistiques;
    private javax.swing.JButton btnTypesIndividus;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
